pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
      - 'master'

name: $(Build.BuildId)

stages:

  - stage: qa
    displayName: 'Run Automation Test - QA'
    dependsOn: []
    jobs:
      - template: /playwright_template.yml
        parameters:
          BASE_URL: ''